print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
a = "Sachin"
b = 23
print(str(a)+str(b))
print("Hello", "World")
print("hi","my","name","sachin",sep='\n')
print("","home","alpine","tarzan","hello-world","",sep='/')
print("root","node","child",sep='->')
print("Hello world",end='\t')
print("This is Sachin")
print("Do you want to continue",end='...')
print("[Y/N]")
print('"one"','"two"','"three"','\n"four"','"five"','"six"','\n"seven"','"eight"','"nine"','"ten"',sep=',')
print('"one"','"two"','"three"',sep=',',end=',')
print('"four"','"five"','"six"',sep=',',end=',')
print('"seven"','"eight"','"nine"','"ten"',sep=',')